import { createFileRoute } from "@tanstack/react-router";

import { PageHero, PublicShell } from "@/components/site/public-shell";
import { Badge } from "@/components/ui/badge";
import { publications, site, timeline } from "@/features/site/content";
import { stations } from "@/features/expeditions/data";

const title = "About the programme | India Polar Science Portal";
const description =
  "History, mandate, stations and governance of India's polar research programme under the Ministry of Earth Sciences, from the 1981 first expedition to the Indian Antarctic Act 2022.";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title },
      { name: "description", content: description },
      { property: "og:title", content: title },
      { property: "og:description", content: description },
    ],
  }),
  component: About,
});

function About() {
  return (
    <PublicShell>
      <PageHero
        eyebrow="About"
        title="Four decades of Indian polar research"
        lead={`${site.name} is the public access point for expedition records, data and outreach produced by the ${site.operator}, the nodal institution for polar and ocean research under the ${site.ministry}.`}
      />

      <section className="mx-auto max-w-7xl px-4 py-16">
        <div className="grid gap-12 lg:grid-cols-3">
          <div className="lg:col-span-2 space-y-6 text-base leading-relaxed">
            <h2 className="font-display text-2xl font-bold">Mandate</h2>
            <p>
              India's polar programme carries three linked responsibilities: to conduct scientific
              research in the Antarctic, Arctic and Southern Ocean; to maintain the logistics and
              station infrastructure that makes that research possible; and to meet the country's
              obligations under the Antarctic Treaty System, the Protocol on Environmental
              Protection and — domestically — the Indian Antarctic Act 2022.
            </p>
            <p>
              Research is delivered through year-round station operations at Maitri and Bharati,
              seasonal Arctic campaigns from Himadri, ship-based Southern Ocean sections aboard ORV
              Sagar Nidhi and ORV Sagar Kanya, and Himalayan cryosphere work from HIMANSH. Data
              generated by every funded project is required to be deposited in this repository with
              standards-compliant metadata and a citable DOI.
            </p>
            <h2 className="pt-4 font-display text-2xl font-bold">Data policy in brief</h2>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                Metadata for every dataset is public from the moment of registration, even where the
                data files are embargoed.
              </li>
              <li>
                A maximum embargo of 24 months from the end of the field season applies, extendable
                only with written approval from the programme director.
              </li>
              <li>
                Datasets are versioned; superseded versions remain resolvable so that published
                analyses stay reproducible.
              </li>
              <li>
                Restricted datasets are released through a reviewed access request, with the decision
                and its rationale recorded in the audit log.
              </li>
            </ul>
          </div>

          <aside className="space-y-4">
            <h2 className="font-display text-xl font-bold">Stations and facilities</h2>
            {stations.map((s) => (
              <article key={s.id} className="rounded-xl border border-border bg-card p-4">
                <div className="flex items-center justify-between gap-2">
                  <h3 className="font-semibold">{s.name}</h3>
                  <Badge variant="secondary">{s.region}</Badge>
                </div>
                <p className="mt-2 text-sm text-muted-foreground">{s.description}</p>
              </article>
            ))}
          </aside>
        </div>
      </section>

      <section className="border-y border-border bg-muted/40">
        <div className="mx-auto max-w-7xl px-4 py-16">
          <h2 className="font-display text-2xl font-bold">Programme milestones</h2>
          <ol className="mt-8 space-y-5 border-l-2 border-accent/40 pl-6">
            {timeline.map((t) => (
              <li key={t.year} className="relative">
                <span
                  className="absolute -left-[31px] top-1.5 size-3 rounded-full bg-accent"
                  aria-hidden
                />
                <span className="font-display text-lg font-semibold">{t.year}</span>
                <p className="mt-1 text-sm text-muted-foreground">{t.event}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-16">
        <h2 className="font-display text-2xl font-bold">Selected publications</h2>
        <ul className="mt-6 divide-y divide-border rounded-xl border border-border bg-card">
          {publications.map((p) => (
            <li key={p.doi} className="p-5">
              <h3 className="font-medium">{p.title}</h3>
              <p className="mt-1 text-sm text-muted-foreground">
                {p.authors} · <em>{p.journal}</em> ({p.year}) · DOI {p.doi}
              </p>
            </li>
          ))}
        </ul>
      </section>
    </PublicShell>
  );
}
