/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExpeditionsIndexRouteImport } from './routes/expeditions.index'
import { Route as ExpeditionsSlugRouteImport } from './routes/expeditions.$slug'
import { Route as LearningIndexRouteImport } from './routes/learning.index'
import { Route as LearningSlugRouteImport } from './routes/learning.$slug'
import { Route as RepositoryIndexRouteImport } from './routes/repository.index'
import { Route as RepositoryIdRouteImport } from './routes/repository.$id'
import { Route as RepositoryUploadRouteImport } from './routes/repository.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsIndexRoute = ExpeditionsIndexRouteImport.update({
  id: '/expeditions/',
  path: '/expeditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsSlugRoute = ExpeditionsSlugRouteImport.update({
  id: '/expeditions/$slug',
  path: '/expeditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningSlugRoute = LearningSlugRouteImport.update({
  id: '/learning/$slug',
  path: '/learning/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryIndexRoute = RepositoryIndexRouteImport.update({
  id: '/repository/',
  path: '/repository/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryIdRoute = RepositoryIdRouteImport.update({
  id: '/repository/$id',
  path: '/repository/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryUploadRoute = RepositoryUploadRouteImport.update({
  id: '/repository/upload',
  path: '/repository/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/expeditions/$slug': typeof ExpeditionsSlugRoute
  '/learning/$slug': typeof LearningSlugRoute
  '/repository/$id': typeof RepositoryIdRoute
  '/repository/upload': typeof RepositoryUploadRoute
  '/expeditions/': typeof ExpeditionsIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/repository/': typeof RepositoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/expeditions/$slug': typeof ExpeditionsSlugRoute
  '/learning/$slug': typeof LearningSlugRoute
  '/repository/$id': typeof RepositoryIdRoute
  '/repository/upload': typeof RepositoryUploadRoute
  '/expeditions': typeof ExpeditionsIndexRoute
  '/learning': typeof LearningIndexRoute
  '/repository': typeof RepositoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/expeditions/$slug': typeof ExpeditionsSlugRoute
  '/learning/$slug': typeof LearningSlugRoute
  '/repository/$id': typeof RepositoryIdRoute
  '/repository/upload': typeof RepositoryUploadRoute
  '/expeditions/': typeof ExpeditionsIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/repository/': typeof RepositoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/expeditions/$slug'
    | '/learning/$slug'
    | '/repository/$id'
    | '/repository/upload'
    | '/expeditions/'
    | '/learning/'
    | '/repository/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/expeditions/$slug'
    | '/learning/$slug'
    | '/repository/$id'
    | '/repository/upload'
    | '/expeditions'
    | '/learning'
    | '/repository'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/expeditions/$slug'
    | '/learning/$slug'
    | '/repository/$id'
    | '/repository/upload'
    | '/expeditions/'
    | '/learning/'
    | '/repository/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExpeditionsSlugRoute: typeof ExpeditionsSlugRoute
  LearningSlugRoute: typeof LearningSlugRoute
  RepositoryIdRoute: typeof RepositoryIdRoute
  RepositoryUploadRoute: typeof RepositoryUploadRoute
  ExpeditionsIndexRoute: typeof ExpeditionsIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
  RepositoryIndexRoute: typeof RepositoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions/': {
      id: '/expeditions/'
      path: '/expeditions'
      fullPath: '/expeditions/'
      preLoaderRoute: typeof ExpeditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions/$slug': {
      id: '/expeditions/$slug'
      path: '/expeditions/$slug'
      fullPath: '/expeditions/$slug'
      preLoaderRoute: typeof ExpeditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$slug': {
      id: '/learning/$slug'
      path: '/learning/$slug'
      fullPath: '/learning/$slug'
      preLoaderRoute: typeof LearningSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/': {
      id: '/repository/'
      path: '/repository'
      fullPath: '/repository/'
      preLoaderRoute: typeof RepositoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/$id': {
      id: '/repository/$id'
      path: '/repository/$id'
      fullPath: '/repository/$id'
      preLoaderRoute: typeof RepositoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/upload': {
      id: '/repository/upload'
      path: '/repository/upload'
      fullPath: '/repository/upload'
      preLoaderRoute: typeof RepositoryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExpeditionsSlugRoute: ExpeditionsSlugRoute,
  LearningSlugRoute: LearningSlugRoute,
  RepositoryIdRoute: RepositoryIdRoute,
  RepositoryUploadRoute: RepositoryUploadRoute,
  ExpeditionsIndexRoute: ExpeditionsIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  RepositoryIndexRoute: RepositoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
